# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '5SKayBaseSwift' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for 5SKayBaseSwift
    
    #UI
    pod 'SnapKit', '~> 3.2.0'
    
    
    #Extension
    pod 'XLSwiftKit'
    
    #Services & Network
    
    #Database
    pod 'SwiftyJSON'
    
    #Language
    pod 'Localize-Swift', '~> 1.7'
    
    
    #Ads
    pod 'Google-Mobile-Ads-SDK'
    
end
